# This is used to build the TechDocs for this component and is referenced here: https://github.com/benwilcock/backstage-catalogs/blob/main/system-polyglot-demo.yml
site_name: 'node-express'
site_description: 'A Node.js sample built using Express'
site_author: user:ben.wilcock

nav:
  - About: 'index.md'