apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: node-express
  namespace: dev
  labels:
    app.kubernetes.io/part-of: node-express
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/language: nodejs
      apps.tanzu.vmware.com/pipeline: test
  source:
    git:
      ref:
        branch: main
      url: https://github.com/benwilcock/node-express
